# Generated by Django 4.1.2 on 2022-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='bracket',
            field=models.JSONField(blank=True, default='afaf'),
            preserve_default=False,
        ),
    ]
