# Generated by Django 4.1.2 on 2022-12-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_bracket_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournaments.tournament'),
        ),
    ]
